sonar.projectKey=kuchmenko_agent-runtime_68e4ee9e-602b-493a-a87d-4536eab122e0
sonar.projectName=agent-runtime

sonar.sources=src
sonar.tests=tests

sonar.exclusions=target/**,**/target/**
sonar.sourceEncoding=UTF-8

sonar.rust.lcov.reportPaths=lcov.info
